### ISSUE TITLE
License Issue

### ISSUE THREAD

**Issue by fakerybakery** [Plachtaa/VALL-E-X#100]
Hello. This package uses `phonemizer`, [which is licensed under GPL because](https://github.com/bootphon/phonemizer/issues/155) it uses `espeak-ng`, [which is licensed under GPL because it uses `espeak`, whose author went offline several years ago.](https://github.com/espeak-ng/espeak-ng/issues/1810) Since GPL requires all upstream projects to be open source and under the same license, does this mean that if we use this package in any projects, those must also be open sourced? (I see that the license of this project is MIT). Thanks in advance!

**Comment by Plachtaa** [comment]
Thanks for your kind reminder. `phonemizer`  and its related usages are now removed from the whole repo & dependencies

**Comment by fakerybakery** [comment]
OK, thanks for this resolution. [I also found an alternative that is MIT-licensed.](https://github.com/as-ideas/DeepPhonemizer)
