### ISSUE TITLE
在推理加速上有任何建议或方向吗？

### ISSUE THREAD

**Issue by Sibozhu** [Plachtaa/VALL-E-X#107]
首先感谢十分优秀的复现，质量非常之高。

尝试了一下部署在 T4 上推理声音克隆需要 100 秒左右生成 6 秒结果，在 A100 上需要 20 秒左右生成同样内容。如果 prompt 固定，请问有更快的推理方式或者代码开发方向吗？类似部署 VLLM 这种？

**Comment by Plachtaa** [comment]
事实上colab的T4，huggingface space的A10G，以及我本地的3060部署模型的RTF均约为1，我建议你检查一下你的code是否有调用GPU

**Comment by Sibozhu** [comment]
多谢！确认使用 T4 GPU 后推理速度提速到了3-5秒的均值，有其他方式复现您提到的 1 秒 RTF 吗？

下面是我现有的代码，在 T4 运行环境下，使用了您 example 中的clone 部分的代码进行编译，两次打印中 'pre_loadmodels()' 大概花掉 11 秒（这个我理解在实际运行中只用 load 第一次即可），之后的'generate_audio()'我尝试了 10 次得到的打印时间都在 3-6 秒这个区间。

`!git clone https://github.com/Plachtaa/VALL-E-X.git
%cd  VALL-E-X

# !readlink -f VALL-E-X

!pip install -r requirements.txt

import torch

device = torch.device("cpu")
if torch.cuda.is_available():
    device = torch.device("cuda", 0)

import sys

sys.path.append('/content/VALL-E-X')

from utils.generation import SAMPLE_RATE, generate_audio, preload_models
from scipy.io.wavfile import write as write_wav
from IPython.display import Audio
from utils.prompt_making import make_prompt

import time

start_time = time.time()

# download and load all models
preload_models()

end_time = time.time()
elapsed_time = end_time - start_time

print(f'time spent on loading models: {elapsed_time}s')

### Use given transcript
make_prompt(name="Paddington", audio_prompt_path="/content/paddington_sample_00.wav",
                transcript="come on then let's get cooking i may look like a hardened criminal to you but I really am innocent and if you are not going to clear my name you could at least help me make this marmalade.")

text_prompt = """
Hi, my name is Paddington, and I'm honored to be around and stay with you. I'll be your best cyber partner!
"""

start_time = time.time()

audio_array = generate_audio(text_prompt, prompt="Paddington")

end_time = time.time()
elapsed_time = end_time - start_time

print(f'time spent on TTS: {elapsed_time}s')


write_wav("paddington_cloned_en.wav", SAMPLE_RATE, audio_array)

# play text in notebook
Audio(audio_array, rate=SAMPLE_RATE)
`

**Comment by Plachtaa** [comment]
RTF是语音合成中的一个常用度量单位，全称为"Real-Time Factor"（实时因子）。它表示语音合成系统合成一段音频所需的时间与实际音频时长之间的比率，所以3~6秒是正常的

**Comment by Sibozhu** [comment]
明白，多谢
