### ISSUE TITLE
prompt中的标点影响

### ISSUE THREAD

**Issue by kli017** [Plachtaa/VALL-E-X#110]
您好，想请教下标点对模型的影响。分别试了一下带标点与不带标点的文本作为text_prompt。发现有标点的生成语音停顿会好些。想问下，是因为在训练时音频对应的文本也是有标点的吗？

**Comment by Plachtaa** [comment]
对

**Comment by kli017** [comment]
@Plachtaa 感谢回复，但是像aishell，aishell3这些数据label中是不带标点的，是用punc restore这种后面加上吗？如果是的话，这样会不会有与音频中的停顿不对应的情况呢

**Comment by Plachtaa** [comment]
其他数据集有标点
