### ISSUE TITLE
Generates different intonations, emphasis, etc. on every new inference for same inputs

### ISSUE THREAD

**Issue by RahulBhalley** [Plachtaa/VALL-E-X#112]
Is there some way to control this randomness of intonations, emphasis, etc. with some random seed generator like Huggingface's Stable Diffusion pipelines?

**Comment by Plachtaa** [comment]
It's basically nucleus sampling as all GPT models do, you can try setting a seed by yourself

**Comment by RahulBhalley** [comment]
Ok, setting different temperature worked for me.
