### ISSUE TITLE
utils/generation.py 和 launch_ui.py 中载入的模型的文件名不一致

### ISSUE THREAD

**Issue by ZYFDroid** [Plachtaa/VALL-E-X#16]
如题。希望可以统一一下模型路径

**Comment by ZYFDroid** [comment]
![image](https://github.com/Plachtaa/VALL-E-X/assets/39429452/2227d2ea-a3df-475d-a349-740fe898ea3b)
补充信息：

**Comment by Plachtaa** [comment]
感谢你的提醒，现已统一两个文件中checkpoint的文件名
