### ISSUE TITLE
訓練設定

### ISSUE THREAD

**Issue by yiwei0730** [Plachtaa/VALL-E-X#2]
有看到介紹說模型是從lifeiteng改過來的，想詢問幾個問題
1. 似乎沒看到bin 資料集的改動和展示
2. 你訓練過程中 source和target會放入不同語言文字嗎?(有經過翻譯的) 
3. 能否透露 python3 bin/trainer.py  後面的設定
4. 您的demo和官方的來說表現相差不遠，您認為再持續加資料集會再表現得更好嗎?

**Comment by Plachtaa** [comment]
1. 为了去掉lhotse, icefall和k2的麻烦依赖所以全删了
2. 不会
3. 基本没怎么改，除了dataloader是自定义的
4. 会

**Comment by yiwei0730** [comment]
使用您這個github能直接做訓練嗎?
還是有缺少某些部分的程式集。

**Comment by yiwei0730** [comment]
了解，感謝您的回覆
最後想請問一下，總共1750小時的資料集，您訓練的steps數量和總用時能否透露

**Comment by Plachtaa** [comment]
大约是800k steps，10 epochs
