### ISSUE TITLE
no such option: --no-error-on-external

### ISSUE THREAD

**Issue by NOTF-API** [Plachtaa/VALL-E-X#23]
pip --version
结果
pip 23.2.1 from C:\Users\XXX\AppData\Local\Programs\Python\Python310\lib\site-packages\pip (python 3.10)

pip install --no-error-on-external -r requirements.txt
结果：
Usage:
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

no such option: --no-error-on-external

python --version
结果：
Python 3.10.11

**Comment by NOTF-API** [comment]
![image](https://github.com/Plachtaa/VALL-E-X/assets/54880414/82a5c95f-9a6b-433b-8af3-8f37b17fe7dc)

**Comment by JoonSumisu** [comment]
虽然我也不知道--no-error-on-external 有什么用，但是你直接 pip install -r 安装也没啥问题，就是要解决几个小问题，安装或者--force-reinstall ，就能解决。

**Comment by NOTF-API** [comment]
D:\github\VALL-E-X>pip install -r requirements.txt --force-reinstall
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple, https://download.pytorch.org/whl/cu118
Ignoring torch: markers 'sys_platform == "darwin"' don't match your environment
Ignoring torchvision: markers 'sys_platform == "darwin"' don't match your environment
Collecting soundfile (from -r requirements.txt (line 3))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/50/ff/26a4ee48d0b66625a4e4028a055b9f25bc9d7c7b2d17d21a45137621a50d/soundfile-0.12.1-py2.py3-none-win_amd64.whl (1.0 MB)
Collecting numpy (from -r requirements.txt (line 4))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/b7/db/4d37359e2c9cf8bf071c08b8a6f7374648a5ab2e76e2e22e3b808f81d507/numpy-1.25.2-cp310-cp310-win_amd64.whl (15.6 MB)
Collecting torch==2.0.1+cu118 (from -r requirements.txt (line 5))
  Using cached https://download.pytorch.org/whl/cu118/torch-2.0.1%2Bcu118-cp310-cp310-win_amd64.whl (2619.1 MB)
Collecting torchvision==0.15.2+cu118 (from -r requirements.txt (line 7))
  Using cached https://download.pytorch.org/whl/cu118/torchvision-0.15.2%2Bcu118-cp310-cp310-win_amd64.whl (4.9 MB)
Collecting tokenizers (from -r requirements.txt (line 9))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/3d/e7/ea70a1a0cd9ad5b4786365edd4042c30037bc4e67ae09c53cd62c6c1b89f/tokenizers-0.13.3-cp310-cp310-win_amd64.whl (3.5 MB)
Collecting encodec (from -r requirements.txt (line 10))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/62/59/e47bbd0542d0e6f4ce9983d5eb458a01d4b42c81e5c410cb9e159b1061ae/encodec-0.1.1.tar.gz (3.7 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting langid (from -r requirements.txt (line 11))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/ea/4c/0fb7d900d3b0b9c8703be316fbddffecdab23c64e1b46c7a83561d78bd43/langid-1.1.6.tar.gz (1.9 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting gdown (from -r requirements.txt (line 12))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/e7/38/e3393edb5fd157abaa54292f31251f8c2ff739673f535990f8a43e69b9dd/gdown-4.7.1-py3-none-any.whl (15 kB)
Collecting unidecode (from -r requirements.txt (line 13))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/be/ea/90e14e807da5a39e5b16789acacd48d63ca3e4f23dfa964a840eeadebb13/Unidecode-1.3.6-py3-none-any.whl (235 kB)
Collecting pyopenjtalk (from -r requirements.txt (line 14))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/f1/69/afdb0b7c8bcf597ccb1a178fde6b7be98125bb38ba488ec94502f489c29d/pyopenjtalk-0.3.2.tar.gz (1.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [44 lines of output]
      setup.py:26: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        _CYTHON_INSTALLED = ver >= LooseVersion(min_cython_ver)
      -- Building for: NMake Makefiles
      CMake Deprecation Warning at CMakeLists.txt:5 (cmake_minimum_required):
        Compatibility with CMake < 3.5 will be removed from a future version of
        CMake.

        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.


      CMake Error at CMakeLists.txt:17 (project):
        Running

         'nmake' '-?'

        failed with:

         绯荤粺鎵句笉鍒版寚瀹氱殑鏂囦欢銆\x82


      CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
      CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
      -- Configuring incomplete, errors occurred!
      CMake is in the system path. Version:               cmake version 3.27.2

      CMake suite maintained and supported by Kitware (kitware.com/cmake).
      Traceback (most recent call last):
        File "C:\Users\NOTF\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\NOTF\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\NOTF\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\NOTF\AppData\Local\Temp\pip-build-env-_05ihu82\overlay\Lib\site-packages\setuptools\build_meta.py", line 162, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "C:\Users\NOTF\AppData\Local\Temp\pip-build-env-_05ihu82\overlay\Lib\site-packages\setuptools\build_meta.py", line 143, in _get_build_requires
          self.run_setup()
        File "C:\Users\NOTF\AppData\Local\Temp\pip-build-env-_05ihu82\overlay\Lib\site-packages\setuptools\build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 191, in <module>
        File "C:\Users\NOTF\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 457, in check_returncode
          raise CalledProcessError(self.returncode, self.args, self.stdout,
      subprocess.CalledProcessError: Command '['cmake', '..', '-DHTS_ENGINE_INCLUDE_DIR=.', '-DHTS_ENGINE_LIB=dummy']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by JoonSumisu** [comment]
额。。 。。。

1. 请阅读主页
❗❗❗ Special Notes ❗❗❗
Japanese g2p tool pyopenjtalk may fail to build during installation, you may ignore it if you don't require Japanese TTS functionality. We are currently searching for more stable substitution.

2. 我说的使用--force-reinstall 是好后，个别module需要重新强制安装

3.pyopenjtalk 的解决方法

https://pypi.org/project/openjtalk/#files

下载后，安装 pip install openjtalk-0.3.0.dev3-cp310-cp310-manylinux2014_x86_64.whl，可以解决。
测试下可以识别出日文了。
