### ISSUE TITLE
默认使用了项目外的路径，希望依赖文件可以调整位置或预载

### ISSUE THREAD

**Issue by 906051999** [Plachtaa/VALL-E-X#28]
* 第一次运行Python样例的时候，在`C:\Users\*\.cache\torch\hub\checkpoints\`路径下下载了`encodec_24khz-d7cc33bc.th`文件
* 执行`python launch-ui.py`后，在`C:\Users\*\AppData\Roaming\nltk_data`路径下下载nltk_data相关文件
> 另：如果网络环境不通畅，会一直卡住没有提醒

**Comment by Plachtaa** [comment]
请把该issue发到nltk和encodec的仓库，我不会改这个

**Comment by Suzixin7894946** [comment]
> * 第一次运行Python样例的时候，在`C:\Users\*\.cache\torch\hub\checkpoints\`路径下下载了`encodec_24khz-d7cc33bc.th`文件
> * 执行`python launch-ui.py`后，在`C:\Users\*\AppData\Roaming\nltk_data`路径下下载nltk_data相关文件
> 
> > 另：如果网络环境不通畅，会一直卡住没有提醒

你好！请问可以分享下encodec_24khz-d7cc33bc这个文件吗？我在复现其他项目时需要这个文件但我找不到在哪里下载

**Comment by 906051999** [comment]
> > * 第一次运行Python样例的时候，在`C:\Users\*\.cache\torch\hub\checkpoints\`路径下下载了`encodec_24khz-d7cc33bc.th`文件
> > * 执行`python launch-ui.py`后，在`C:\Users\*\AppData\Roaming\nltk_data`路径下下载nltk_data相关文件
> > 
> > > 另：如果网络环境不通畅，会一直卡住没有提醒
> 
> 你好！请问可以分享下encodec_24khz-d7cc33bc这个文件吗？我在复现其他项目时需要这个文件但我找不到在哪里下载

无法上传，爱莫能助
