### ISSUE TITLE
为什么二次元的声音合成效果较好？

### ISSUE THREAD

**Issue by danfouer** [Plachtaa/VALL-E-X#29]
是因为二次元声音吐字清晰，特征明显还是因为用于标注训练的样本多啊？

**Comment by Plachtaa** [comment]
因为普遍吐字清晰且录音设备较好，没有环境杂音

**Comment by by517840374** [comment]
所以有没有兄弟分享分享不错的御姐npz？
我先来，质量有点拉跨，听着试试
链接：https://pan.baidu.com/s/1rf4qmGG7kDU-mLfzsbtzUQ?pwd=bk38 
提取码：bk38

**Comment by danfouer** [comment]
那能不能针对my professional voice clone (PVC)做专门的优化，另外，我输出长文本中文总感觉有股外国人学说中文的感觉，是不是把训练集中的英文和日文去掉之后会好一些？

**Comment by danfouer** [comment]
> 因为普遍吐字清晰且录音设备较好，没有环境杂音

f0高？F0 Contours， 全称为Fundamental Frequency Contours

**Comment by Plachtaa** [comment]
To be honest, I don't have a answer to your question, which is beyond my knowledge and ability.
