### ISSUE TITLE
How to get vallex-checkpoint.pt?

### ISSUE THREAD

**Issue by EricKong1985** [Plachtaa/VALL-E-X#3]
File "D:\codes\VALL-E-X\py\lib\site-packages\torch\serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './vallex-checkpoint.pt'

**Comment by ZYFDroid** [comment]
just download the checkpoint file from google drive and put it in the project root directory. 
![image](https://github.com/Plachtaa/VALL-E-X/assets/39429452/ad7105e8-96f9-485c-8ab7-66b876488338)

**Comment by EricKong1985** [comment]
thank you very much for your information!
