### ISSUE TITLE
求助，还是不会启动

### ISSUE THREAD

**Issue by qhyj** [Plachtaa/VALL-E-X#30]
1、将中文说明反复观看，先是用一天时间 找了个教程安装了深度计算的环境，包括anaconda+python3.10+pycharm+cuda+cudnn+pytorch
2、再看文档说明，说要安装ffmpeg，在CSDN找了个教程也安上了（参考教程：https://blog.csdn.net/kakangel/article/details/128160587）
3、我最早看到大佬的视频先来到github上下载了源文件，放置在了：E:\AI\VALL-E-X-master
4、又下载了预训练模型，将其放在了E:\AI\VALL-E-X-master下面，但说明上要将它放在checkpoints文件夹下，所以又在软件根目录建了个文件夹起名为checkpoints将预训练模型放进去
5、将E:\AI\VALL-E-X-master\ffmpeg\bin也加入了系统变量Patch中
6、然后按本地安装装的，打开anaconda,先通过conda activate py3.10激活PY3.10的环境，然后在里面输入
pip install -r E:\AI\VALL-E-X-master\requirements.txt
好像是安装了一堆东西是即时下载的，完事后，就是启动网页界面了
7、我又在anaconda的py3.10的环境下面输入：python E:\AI\VALL-E-X-master\launch-ui.py，如果如下代码：

(base) C:\Users\PFP>conda activate py3.10

(py3.10) C:\Users\PFP>python E:\AI\VALL-E-X-master\launch-ui.py
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\PFP\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.
C:\Users\PFP\.conda\envs\py3.10\lib\site-packages\whisper\timing.py:58: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  def backtrace(trace: np.ndarray):
Use 32 cpu cores for computing
Traceback (most recent call last):
  File "E:\AI\VALL-E-X-master\launch-ui.py", line 52, in <module>
    text_tokenizer = PhonemeBpeTokenizer(tokenizer_path="./utils/g2p/bpe_69.json")
  File "E:\AI\VALL-E-X-master\utils\g2p\__init__.py", line 13, in __init__
    self.tokenizer = Tokenizer.from_file(tokenizer_path)
Exception: 系统找不到指定的路径。 (os error 3)

(py3.10) C:\Users\PFP>

就是不会启动了，希望大神指点下

**Comment by ZYFDroid** [comment]
建议：
先cd到VALL-E-X的根目录再启动。这个项目里很多地方用的相对路径
```cmd
E:
cd E:\AI\VALL-E-X-master\
python.exe launch-ui.py
```

**Comment by qhyj** [comment]
(base) C:\Users\PFP>conda activate py3.10

(py3.10) C:\Users\PFP>cd E:\AI\VALL-E-X-master\

(py3.10) C:\Users\PFP>python launch-ui.py
python: can't open file 'C:\\Users\\PFP\\launch-ui.py': [Errno 2] No such file or directory

(py3.10) C:\Users\PFP>
大神，你看看按你说的好像还是不行

**Comment by qhyj** [comment]
![1](https://github.com/Plachtaa/VALL-E-X/assets/143189491/9c33d151-2ce5-4ac5-8bb5-592dd3c2d582)

**Comment by ZYFDroid** [comment]
当你在cmd中，想要切换到一个其他盘的路径的时候，你需要手动输入一个 `E:` 来切换到其他盘。
例如当我想要从C盘切换到Q盘的时候：
```cmd
rem That doesn't work 
C:\Users\ZYFDroid>cd Q:\

C:\Users\ZYFDroid>


rem You should use drive letter plus a colon to change to another drive 
C:\Users\ZYFDroid>Q:
rem and then cd to the target directory. 
Q:\>cd Q:\MachineLearning\VALL-E\VALL-E-X

Q:\MachineLearning\VALL-E\VALL-E-X>
```

**Comment by qhyj** [comment]
![2](https://github.com/Plachtaa/VALL-E-X/assets/143189491/43b48ebe-a15f-4a7d-a0ed-d1a51f28ec13)
 十分感谢大神的无私帮助
