### ISSUE TITLE
【bug】[nltk_data] Error loading punkt: <urlopen error [Errno 11004]

### ISSUE THREAD

**Issue by Ikaros-521** [Plachtaa/VALL-E-X#36]
第一次启动时，会下载nltk相关内容。 
```
(base) D:\GitHub_pro\VALL-E-X>python launch-ui.py
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Administrator\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.
```  
第二次启动时，报错无法加载  

```
(base) D:\GitHub_pro\VALL-E-X>python launch-ui.py
[nltk_data] Error loading punkt: <urlopen error [Errno 11004]
[nltk_data]     getaddrinfo failed>
```
本地文件是存在的  
![image](https://github.com/Plachtaa/VALL-E-X/assets/40910637/a0cf7646-63b9-4d42-8855-5f718e078928)

**Comment by Ikaros-521** [comment]
呃，有时候成功，有时候不成功，难绷

**Comment by Plachtaa** [comment]
感谢佬的反馈

我这边重复运行下载`punkt`的代码时并无异常，猜测有概率是网络问题

**Comment by Ikaros-521** [comment]
> 感谢佬的反馈
> 
> 我这边重复运行下载`punkt`的代码时并无异常，猜测有概率是网络问题

大佬，是不是直接下载到项目路径加载好一点0.0
我看langchain-ChatGLM是内置的

**Comment by Plachtaa** [comment]
很抱歉，我不是很懂nltk的这个问题😥

不过根据你的建议，我可以尝试修改一下code让它从本地读取

**Comment by Plachtaa** [comment]
当然如果佬知道怎么操作的话，希望可以提一个PR拜托了🙏，我这边可能还要学一下

**Comment by Ikaros-521** [comment]
ps：whisper的medium模型感觉也需要内置一下，丢在c盘挺占容量的0.0
![AQKNZ 754@IWX}`@2PH9M~6](https://github.com/Plachtaa/VALL-E-X/assets/40910637/9f7a2539-064e-4863-ad9a-afb80802a254)

**Comment by hkzbiyx** [comment]
> 很抱歉，我不是很懂nltk的这个问题😥
> 
> 不过根据你的建议，我可以尝试修改一下code让它从本地读取

要不直接提供离线的nltk_data资源文件，新开个./checkpoints/nltk_data 放这些东西，省得重复下载了。

**Comment by Plachtaa** [comment]
感谢 @hkzbiyx 大佬，Whisper以及nltk的下载路径已经全部更改到项目路径下了

**Comment by Ikaros-521** [comment]
> 感谢 @hkzbiyx 大佬，Whisper以及nltk的下载路径已经全部更改到项目路径下了

哇 什么效率哇 大佬都不睡觉的吗
你们真的  我哭死😭😭😭
