### ISSUE TITLE
voice cloning problem

### ISSUE THREAD

**Issue by SaltedSlark** [Plachtaa/VALL-E-X#4]
非常好的工作！
我遇到一个问题，text_prompt文本稍微长一点，效果就拉了，请问是怎么回事？

**Comment by ZYFDroid** [comment]
目前阶段的局限性。可以试试分段生成
![image](https://github.com/Plachtaa/VALL-E-X/assets/39429452/fb0dd11b-db01-43ef-bbf0-7c289868fc4e)

**Comment by Plachtaa** [comment]
训练时使用的音频长度均没有超过22秒，所以只有在audio prompt和生成audio总长度加起来小于22秒时才能保证最佳效果

**Comment by EricKong1985** [comment]
训练数据的长度有限吗？

**Comment by Plachtaa** [comment]
已加入FAQ
