### ISSUE TITLE
How to make it run on macos

### ISSUE THREAD

**Issue by aqgasa** [Plachtaa/VALL-E-X#42]
I got the following error:
"NotImplementedError: cannot instantiate 'WindowsPath' on your system"

To fix this I changed line number 12 in file launch-ui.py
FROM:
`elif platform.system().lower() == 'linux':`
TO:
`else:`

It runs well on M2.

**Comment by Plachtaa** [comment]
Noted, thanks for your advice. I've updated UI script as you suggested.

**Comment by marisbasha** [comment]
Isn't it better to remove the WindowsPath from the checkpoint 'exp_dir' and 'manifest_dir'?
