### ISSUE TITLE
Adding a new language

### ISSUE THREAD

**Issue by bluemix** [Plachtaa/VALL-E-X#43]
what is the possibility to add a new language? e.g., Arabic? is there a guide or something i can read?
thanks in advance.

**Comment by Plachtaa** [comment]
Please refer to #14

**Comment by Plachtaa** [comment]
Closing this issue due to long term of inactivity

**Comment by MuhammadShifa** [comment]
Hi @bluemix ,
Have you trained it for Arabic, I am also planning to train it for Arabic language.
