### ISSUE TITLE
'NoneType' object has no attribute 'inference'

### ISSUE THREAD

**Issue by bmox** [Plachtaa/VALL-E-X#45]
Can anyone help me ?
![image](https://github.com/Plachtaa/VALL-E-X/assets/62886280/4e373983-8488-4261-8658-099926665f95)

**Comment by Plachtaa** [comment]
Same as #47 , you need to run `preload_models()` before running `generate_audio()`

**Comment by Plachtaa** [comment]
Close this issue as #47 is solved.
