### ISSUE TITLE
 'NoneType' object has no attribute 'inference'

### ISSUE THREAD

**Issue by parzoe** [Plachtaa/VALL-E-X#47]
Wehn I'm trying to use my custom prompt I got this error

`raceback (most recent call last):
  File "/home/mike/Documents/ai/VALL-E-X/test_prompt.py", line 7, in <module>
    audio_array = generate_audio(text_prompt, prompt="trump")
  File "/home/mike/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/mike/Documents/ai/VALL-E-X/utils/generation.py", line 125, in generate_audio
    encoded_frames = model.inference(
AttributeError: 'NoneType' object has no attribute 'inference'`

here is my code:

` from utils.generation import SAMPLE_RATE, generate_audio, preload_models
from scipy.io.wavfile import write as write_wav

text_prompt = """
Hey, Traveler, Listen to this, This machine has taken my voice, and now it can talk just like me!
"""
audio_array = generate_audio(text_prompt, prompt="custom_prompt")

write_wav("inputAudio/custom_prompt_result.wav", SAMPLE_RATE, audio_array)`

**Comment by parzoe** [comment]
#45 the same issue here. We were posting almost the same time

**Comment by bmox** [comment]
ha ha

**Comment by Plachtaa** [comment]
Sorry I didn't write clearly in README, you still need to run `preload_models()` before running `generate_audio()`
