### ISSUE TITLE
合成质量还是差强人意

### ISSUE THREAD

**Issue by victorx98** [Plachtaa/VALL-E-X#49]
虽然是0 shot，但是质量还是很重要。 可以再提供一个选择：增加训练语料和时长，提供更完美的合成质量

**Comment by Plachtaa** [comment]
你说得对，但是收集数据要时间，训练要钱，该项目仅为小规模复现，意图证明这个idea的可行性，所以很抱歉不会进行进一步的训练。

**Comment by Plachtaa** [comment]
README已注明训练code来源
