### ISSUE TITLE
是否有考虑更换其他音质更好的codec呢

### ISSUE THREAD

**Issue by innnky** [Plachtaa/VALL-E-X#5]
例如，在不重新训练模型的情况下，应该可以使用[Vocos](https://github.com/charactr-platform/vocos) 直接替换掉encodec的decoder
如果重新训练模型的话，有[AcademiCodec](https://github.com/yangdongchao/AcademiCodec) 、[descript-audio-codec](https://github.com/descriptinc/descript-audio-codec) 等一系列音质更好的codec可以使用？

**Comment by Plachtaa** [comment]
感谢你指出这个问题，Encodec在重建某些较为尖锐的音色时音质确实非常差
如果有时间，我会尝试使用你所建议的vocos替代Encodec的解码器
受制于成本，重新训练模型是不会考虑的，请见谅

**Comment by Plachtaa** [comment]
经实证，在`num_quantizers`均为8的设定下，decript-audio-codec的音质确实有显著提升
vocos与encodec的音质相差不大
AcadamiCodec暂未测试
所以，目前暂时不会替换codec。如果有时间的话，我会考虑在训练集音频上微调vocos来改善音质。
