### ISSUE TITLE
Updated phonemizer broke install with requirements.txt

### ISSUE THREAD

**Issue by AHEKOT** [Plachtaa/VALL-E-X#54]
after install it says 
"File "/Users/ahekot/PycharmProjects/Python3.10_test/VALL-E-X/launch-ui.py", line 29, in <module>
    from data.tokenizer import (
  File "/Users/ahekot/PycharmProjects/Python3.10_test/VALL-E-X/data/tokenizer.py", line 26, in <module>
    from phonemizer.backend.espeak.language_switch import LanguageSwitch
ModuleNotFoundError: No module named 'phonemizer.backend.espeak.language_switch'; 'phonemizer.backend.espeak' is not a package

You can fix this by downgrading phonemizer with pip install phonemizer==3.2.0

**Comment by Plachtaa** [comment]
Updated
