### ISSUE TITLE
是否内置依赖文件

### ISSUE THREAD

**Issue by hkzbiyx** [Plachtaa/VALL-E-X#55]
我准备把encodec等的依赖文件从.cache更改到项目路径下，如果直接内置在项目中可以减少网络不稳定带来的影响，但会增加大概140MB的大小。是内置好还是单纯改路径比较好？

**Comment by Plachtaa** [comment]
希望可以尽量避免将Encodec，Vocos等模型文件直接上传到仓库中，如果可以的话，最好只更改下载路径

**Comment by hkzbiyx** [comment]
> 希望可以尽量避免将Encodec，Vocos等模型文件直接上传到仓库中，如果可以的话，最好只更改下载路径，非常感谢你

好的，到时候有空我提个PR
