### ISSUE TITLE
如何得到一个比较好的npz模型？

### ISSUE THREAD

**Issue by EricKong1985** [Plachtaa/VALL-E-X#6]
https://github.com/Plachtaa/VALL-E-X/assets/8405704/ee675145-405c-4f78-be5d-b19e3dec8c46

如上面的视频，如何才能得到一个比较好的npz文件，我在网上找了一个6秒的视频，到处音频，生成npz文件。生成的voice，噪音比较大？
请教一下大家如何生成做得到一个比较的npz文件？能够生成清晰一点的voice？
需要音频的长度要求？
需要声音的频率要求？
需要不需要一个比较安静的环境录音？
但是我又想有点 环境音存在，是否能够做到？

**Comment by EricKong1985** [comment]
https://github.com/Plachtaa/VALL-E-X/assets/8405704/f5bf0720-eb46-412c-86cc-3ad5d223bc67
有没有一种方式，设置设定一个seed，等到两次比较稳定的声音输出，例如第一个文件的声音就比较低成，第二次输出的声音就比较兴奋

**Comment by Plachtaa** [comment]
一般来讲，干净的人声依然是最理想的选择。环境音变数太大

**Comment by EricKong1985** [comment]
能否这样子理解，这些稀奇古怪的声音和语调波动，主要是的由于环境音做成的，导致了npz的模型有点不“纯净”

**Comment by Plachtaa** [comment]
我不知道，请您自己多尝试。
