### ISSUE TITLE
How to get emotions?

### ISSUE THREAD

**Issue by konbraphat51** [Plachtaa/VALL-E-X#64]
How to generate voice with emotion like "amused" or "sleepy"?

**Comment by Plachtaa** [comment]
Use an angry audio prompt to get a prompt contains emotion of anger
Similarly, use an sleepy audio prompt to get a prompt contains emotion of sleepiness

**Comment by konbraphat51** [comment]
Thank you for your reply.
When cloning, how could I make my audio prompt containing selected emotion?

Also, when making text prompt, how could I specify emotion I want? I would be happy if you give me a simple example.

**Comment by Plachtaa** [comment]
See demo page for how a emotional prompt is made

**Comment by konbraphat51** [comment]
Oh, sorry. I misunderstood.

This model automatically convert original voice data to the aimed voice, but the emotion remained, right?
I thought I have to somehow edit text prompt.

Thank you for your kindness.
