### ISSUE TITLE
Dataset Copyright

### ISSUE THREAD

**Issue by ghost** [Plachtaa/VALL-E-X#66]
Your demo page states that you have "self-gathered" data.
I would like to know the details of the data breakdown.
Does this include data that may be problematic for commercial use, such as animation, movies, YouTube, etc.?

**Comment by Subarasheese** [comment]
You do realize most big-tech company straight out make use of data of their users to train their AI or "improve their products", right? Or straight out selling private data from users without their consent for advertisers and such.

Why don't you go ask them first before complaining on a free and open source software project?

This corporate bootlicking is beyond me, what do you have to gain from it?

**Comment by Plachtaa** [comment]
Thanks for your concern about this topic.

The "self-gathered" data mentioned in the demo page are mainly voice-text pairs extracted from several games, which was initially intended to use for teaching the model speak in various Anime/Comic-like voices. These voices usually differs a lot from the way normal people speak, so I believe this a necessary step to make the model more versatile.

Another important reason for doing so is that there are very few Japanese corpus available (unlike Chinese & Japanese), so I have to get additional (300+ hours) in this way, or else there will be no Japanese support.

**Comment by Subarasheese** [comment]
> Big Tech has already been sued several times and has the manpower and money to deal with it. But if we as individual developers get sued, will anyone protect us? The logic of "other big companies are doing it, so forgive me" won't hold up in court. Knowing the details of the dataset in advance is a good way to protect yourself.
> 
> As long as the models are distributed under a commercially available MIT license, it should be beneficial to both OSS developers and users to share a little more "self-gathered" data detail. Rather than rushing to deal with problems after they occur.

In most jurisdictions, derivative work (which AI fits in) on copyrighted material is not a copyright violation as long as you are not profiting off it / taking commercial advantage, so as long as you use those models the way they are meant to be used, it should not be a problem
