### ISSUE TITLE
try to train VALL-E-X but the results are weird

### ISSUE THREAD

**Issue by cnlinxi** [Plachtaa/VALL-E-X#67]
hi, thank you for this work.
I try to train this VALL-E-X with LibriTTS and Aishell-1, but get weird result. Do you have any idea? thanks a lot
I use train code from [lifeiteng/vall-e](https://github.com/lifeiteng/vall-e), tensorboard is here:

![image](https://github.com/Plachtaa/VALL-E-X/assets/11946496/42dde9c0-3a12-48df-ade6-d0a71a68d753)
![image](https://github.com/Plachtaa/VALL-E-X/assets/11946496/f4cbe197-de2e-473e-950b-767867e78904)

train scripts:
```shell
python train.py \
        --train-stage 1 \
        --world-size 2 \
        --num-workers 2 \
        --max-duration 3750 \
        --dtype "float32" \
        --save-every-n 10000 \
        --valid-interval 20000 \
        --model-name valle \
        --share-embedding true \
        --norm-first true \
        --add-prenet true \
        --decoder-dim 1024 \
        --nhead 16 \
        --num-decoder-layers 12 \
        --prefix-mode 1 \
        --base-lr 0.05 \
        --warmup-steps 200 \
        --average-period 0 \
        --num-epochs 20 \
        --start-epoch 15 \
        --start-batch 0 \
        --accumulate-grad-steps 8 \
        --exp-dir "${exp_dir}"
```

```shell
python train.py \
        --train-stage 2 \
        --world-size 2 \
        --num-workers 2 \
        --max-duration 3750 \
        --dtype "float32" \
        --save-every-n 10000 \
        --valid-interval 20000 \
        --model-name valle \
        --share-embedding true \
        --norm-first true \
        --add-prenet true \
        --decoder-dim 1024 \
        --nhead 16 \
        --num-decoder-layers 12 \
        --prefix-mode 1 \
        --base-lr 0.05 \
        --warmup-steps 200 \
        --average-period 0 \
        --num-epochs 100 \
        --start-epoch 41 \
        --start-batch 0 \
        --accumulate-grad-steps 4 \
        --exp-dir "${exp_dir}"
```

**Comment by Plachtaa** [comment]
I think the tensorboard you presented here indicates the training is working as expect. There is nothing weird.

**Comment by cnlinxi** [comment]
> I think the tensorboard you presented here indicates the training is working as expected. There is nothing weird.

@Plachtaa Thanks for your reply. I'm sorry that I forget to post the synthesized speech. The synthesized speech is still incomprehensible after NAR training to 40 epochs. This does not seem to be expected (audio is in zip file):

[This four hole egg frying pan is very useful.zip](https://github.com/Plachtaa/VALL-E-X/files/12508787/This.four.hole.egg.frying.pan.is.very.useful.zip)

![image](https://github.com/Plachtaa/VALL-E-X/assets/11946496/30882356-0829-4a46-a80c-2c16d7bd8043)

prompt audio is 3s and use the prompt with pretrained model in this repo is ok.

Do you have any idea on this bug? Thanks a lot.

**Comment by kli017** [comment]
@cnlinxi Hello, Are you using the recipes in lifeiteng/valle to prepare the data?

**Comment by cnlinxi** [comment]
> @cnlinxi Hello, Are you using the recipes in lifeiteng/valle to prepare the data?

I wrote a data processing process myself.

**Comment by KunZhou9646** [comment]
Hi! I would like to know how does your result sound like evetually..I got similar audio quality as your attached before..
