### ISSUE TITLE
Can't it be called with API or python？

### ISSUE THREAD

**Issue by KaiJia2017** [Plachtaa/VALL-E-X#73]
test.py：

from utils.generation import SAMPLE_RATE, generate_audio, preload_models
from scipy.io.wavfile import write as write_wav
from IPython.display import Audio

# download and load all models
preload_models()

# generate audio from text
text_prompt = """
Hello, my name is Nose. And uh, and I like hamburger. Hahaha... But I also have other interests such as playing tactic toast.
"""
audio_array = generate_audio(text_prompt)

# save audio to disk
write_wav("vallex_generation.wav", SAMPLE_RATE, audio_array)

# play text in notebook
Audio(audio_array, rate=SAMPLE_RATE)

cmd：

G:\GitFork\VALL-E-X>py test.py
Traceback (most recent call last):
  File "G:\GitFork\VALL-E-X\test.py", line 1, in <module>
    from utils.generation import SAMPLE_RATE, generate_audio, preload_models
  File "G:\GitFork\VALL-E-X\utils\__init__.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'

**Comment by Plachtaa** [comment]
Please install `torch` properly
