### ISSUE TITLE
语音合成效果不好啊，稍微长点就不行了

### ISSUE THREAD

**Issue by futureflsl** [Plachtaa/VALL-E-X#75]
代码：
from utils.generation import SAMPLE_RATE, generate_audio, preload_models
from scipy.io.wavfile import write as write_wav
from IPython.display import Audio

preload_models()

text_prompt = """
日常通勤用共享单车代步已成为不少人的选择，许多普通骑行爱好者也喜欢骑共享单车在户外骑行，既方便又锻炼身体。
近日，有网友反映，在骑完共享单车锁车时，扣费达十几元甚至数十元，远超以往正常骑行价格。细看账单才知道，除了共享单车骑行单价已上涨外，更要注意停放区域，以免产生调度费。
"""
audio_array = generate_audio(text_prompt)

write_wav("result.wav", SAMPLE_RATE, audio_array)
Audio(audio_array, rate=SAMPLE_RATE)

这是合成效果，听听吧，后面都和文字对不上而且合成不出来
[result.zip](https://github.com/Plachtaa/VALL-E-X/files/12543292/result.zip)

**Comment by Plachtaa** [comment]
See https://github.com/Plachtaa/VALL-E-X#why-the-model-fails-to-generate-long-text for answer.
Use `infer long text` functionality in the Web UI if you need to synthesize a long paragraph.

**Comment by Plachtaa** [comment]
[audio (1).webm](https://github.com/Plachtaa/VALL-E-X/assets/112609742/e2ad9bcf-b9ae-4db8-99d4-1c33a0cbfda6)
Appended a synthesized demo using the text you have given.
