### ISSUE TITLE
Add  Vocos  information  to the README.

### ISSUE THREAD

**Issue by SsZyz** [Plachtaa/VALL-E-X#89]
Perhaps you need to add the download path and other information of Vocos model files to the README.
I'm in Chinese Mainland, I can't visit huggingface, I need download path and file relative path.

Here is my error msg:
Traceback (most recent call last):
  File "/home/orangepi/VALL-E-X/launch-ui.py", line 107, in <module>
    vocos = Vocos.from_pretrained('charactr/vocos-encodec-24khz').to(device)
  File "/home/orangepi/.local/lib/python3.10/site-packages/vocos/pretrained.py", line 65, in from_pretrained
    config_path = hf_hub_download(repo_id=repo_id, filename="config.yaml")
  File "/home/orangepi/.local/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn    return fn(*args, **kwargs)
  File "/home/orangepi/.local/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1291, in hf_hub_download
    raise LocalEntryNotFoundError(
huggingface_hub.utils._errors.LocalEntryNotFoundError: Connection error, and we cannot find the requested files in the disk cache. Please try again or make sure your Internet connection is on.

**Comment by hkzbiyx** [comment]
I'm working on the code to fix this issue, and you can use a VPN to download files pytorch_model.bin and config.yaml from https://huggingface.co/charactr/vocos-encodec-24khz/tree/main  in the meantime. 
If you're on Windows, put them in a folder like this: 
C:\Users\%username%\.cache\huggingface\hub\models--charactr--vocos-encodec-24khz\snapshots\79e727a494e086711ae32d6edb06bef4aed054e2.

**Comment by hkzbiyx** [comment]
I'm working on the code to fix this issue, and you can use a VPN to download files pytorch_model.bin and config.yaml from https://huggingface.co/charactr/vocos-encodec-24khz/tree/main in the meantime.
If you're on Windows, put them in a folder like this:
C:\Users\%username%\.cache\huggingface\hub\models--charactr--vocos-encodec-24khz\snapshots\79e727a494e086711ae32d6edb06bef4aed054e2.

**Comment by SsZyz** [comment]
@hkzbiyx I have downloaded these two files from other channels and am currently researching their paths in a Linux environment. I am using Raspberry Pi

**Comment by hkzbiyx** [comment]
> @hkzbiyx I have downloaded these two files from other channels and am currently researching their paths in a Linux environment. I am using Raspberry Pi

The command `huggingface-cli scan-cache -v` will show you the cache path in the LOCAL PATH. The cache path in Linux maybe something like this: `/home/wauplin/.cache/huggingface/hub/models--charactr--vocos-encodec-24khz/snapshots/9338f7b671827df886678df2bdd7cc7b4f36dffd`

**Comment by hkzbiyx** [comment]
I will move these dependency files to the project folder in the future. But the network problem is still difficult to deal with.

**Comment by SsZyz** [comment]
Things may not be as simple ,I may need to download tokens and assets or other files from huggingface to use Vocos 
Fxxk Network

**Comment by hkzbiyx** [comment]
> Things may not be as simple ,I may need to download tokens and assets or other files from huggingface to use Vocos Fxxk Network

Let me take a look at your error message and see what's wrong.

**Comment by SsZyz** [comment]
@hkzbiyx 
this is  launch-ui.py‘s error,  it points to the issue of downloading, It looks like some file was not downloaded, causing huggingface_hub can't init  
orangepi@orgpi:~/VALL-E-X$ python -X utf8 launch-ui.py 
default encoding is utf-8,file system encoding is utf-8
You are using Python version 3.10.12
/home/orangepi/.local/lib/python3.10/site-packages/whisper/timing.py:58: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  def backtrace(trace: np.ndarray):
Traceback (most recent call last):
  File "/home/orangepi/VALL-E-X/launch-ui.py", line 49, in <module>
    from vocos import Vocos
  File "/home/orangepi/.local/lib/python3.10/site-packages/vocos/__init__.py", line 1, in <module>
    from vocos.pretrained import Vocos
  File "/home/orangepi/.local/lib/python3.10/site-packages/vocos/pretrained.py", line 5, in <module>
    from huggingface_hub import hf_hub_download
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/home/orangepi/.local/lib/python3.10/site-packages/huggingface_hub/__init__.py", line 322, in __getattr__
    submod = importlib.import_module(submod_path)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/orangepi/.local/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1292
    "Connection error, and we cannot find the requested files in"
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
------------------------------------------------------------------------------------
this is huggingface env info, I have not token path, assets cache path on my micro computer 
orangepi@orgpi:~/VALL-E-X$ huggingface-cli env

Copy-and-paste the text below in your GitHub issue.

- huggingface_hub version: 0.16.4
- Platform: Linux-5.10.110-rockchip-rk3588-aarch64-with-glibc2.35
- Python version: 3.10.12
- Running in iPython ?: No
- Running in notebook ?: No
- Running in Google Colab ?: No
- Token path ?: /home/orangepi/.cache/huggingface/token
- Has saved token ?: False
- Configured git credential helpers: 
- FastAI: N/A
- Tensorflow: N/A
- Torch: 2.0.1
- Jinja2: 3.1.2
- Graphviz: N/A
- Pydot: N/A
- Pillow: 10.0.0
- hf_transfer: N/A
- gradio: 3.44.0
- tensorboard: N/A
- numpy: 1.24.4
- pydantic: 2.3.0
- aiohttp: N/A
- ENDPOINT: https://huggingface.co
- HUGGINGFACE_HUB_CACHE: /home/orangepi/.cache/huggingface/hub
- HUGGINGFACE_ASSETS_CACHE: /home/orangepi/.cache/huggingface/assets
- HF_TOKEN_PATH: /home/orangepi/.cache/huggingface/token
- HF_HUB_OFFLINE: False
- HF_HUB_DISABLE_TELEMETRY: False
- HF_HUB_DISABLE_PROGRESS_BARS: None
- HF_HUB_DISABLE_SYMLINKS_WARNING: False
- HF_HUB_DISABLE_EXPERIMENTAL_WARNING: False
- HF_HUB_DISABLE_IMPLICIT_TOKEN: False
- HF_HUB_ENABLE_HF_TRANSFER: False

**Comment by hkzbiyx** [comment]
@SsZyz 

Maybe this can solve the problem. Create a directory tree like this. 


    └─models--charactr--vocos-encodec-24khz
        ├─refs
        │      main
        │
        └─snapshots
            └─test
                    config.yaml
                    pytorch_model.bin

That is, create two folders `refs` and `snapshots` under folder `models--charactr--vocos-encodec-24khz`, create a file named main in folder `refs`, write test in it, create a folder named test under folder `snapshots`, and put files `config.yaml` and `pytorch_model.bin` in the test folder.

**Comment by SsZyz** [comment]
Still failed, same error msg

**Comment by hkzbiyx** [comment]
Your error might be different from what I reproduced. I only have a temporary solution. Please tell me where you put your `pytorch_model.bin` file and `config.yaml` file. I can only give you a code, and you need to manually modify the `/home/orangepi/.local/lib/python3.10/site-packages/vocos/pretrained.py` file to make it read the path directly.

**Comment by hkzbiyx** [comment]
@SsZyz 
If possible, could you please give me your email address or other ways to contact you? I want to send you some test files to see where the problem lies.

**Comment by SsZyz** [comment]
@hkzbiyx tangleile@outlook.com

**Comment by SsZyz** [comment]
@hkzbiyx After solving the network, the files is downloaded to "blobs" dir first and linked to the "snapshots" dir after
```
orangepi@orgpi:~/.cache/huggingface/hub/models--charactr--vocos-encodec-24khz/snapshots/79e727a494e086711ae32d6edb06bef4aed054e2$ ll
total 12
drwxrwxr-x 2 orangepi orangepi 4096 Sep 19 01:19 ./
drwxrwxr-x 4 orangepi orangepi 4096 Sep 19 01:19 ../
lrwxrwxrwx 1 orangepi orangepi   52 Sep 19 01:19 config.yaml -> ../../blobs/943725ef0c2ce567f75551dfed0cf5c4e01c8908
lrwxrwxrwx 1 orangepi orangepi   76 Sep 19 01:19 pytorch_model.bin -> ../../blobs/258052d0ff62159a04ce32ba417e980476ca1b01451e9907204f4fa5fbac4f00
```

**Comment by hkzbiyx** [comment]
I really appreciate your help! It looks like linux and windows operate differently in these systems.😢 I will conduct more tests to minimize bugs.

**Comment by guanyunhong1012** [comment]
Hello,I have encountered the same problem,on Unbantu.Please help me, thank you！

**Comment by hkzbiyx** [comment]
> Hello,I have encountered the same problem,on Unbantu.Please help me, thank you！

Download this file.
https://pan.baidu.com/s/123sbEQRvbWJrx728JwgqSg?pwd=h2gi 

Run this:
`tar zxvf vocos.tar.gz -C ~/.cache/huggingface/hub`

This may solve the problem.

**Comment by guanyunhong1012** [comment]
> > Hello,I have encountered the same problem,on Unbantu.Please help me, thank you！
> 
> Download this file. https://pan.baidu.com/s/123sbEQRvbWJrx728JwgqSg?pwd=h2gi
> 
> Run this: `tar zxvf vocos.tar.gz -C ~/.cache/huggingface/hub`
> 
> This may solve the problem.
Thanks, the problem has been resolved

**Comment by fedhong** [comment]
> @hkzbiyx I have downloaded these two files from other channels and am currently researching their paths in a Linux environment. I am using Raspberry Pi

Where did you download these two files? I also cannot access huggingface.co

**Comment by SsZyz** [comment]
不能访问huggingface.co的话还是说中文吧.
只能尝试科学上网.我之前在百度贴吧找了个老哥分享的Windows环境下的VALL-E-X压缩包,人工拷贝模型文件到Linux系统中的Python环境中去也不能用,最后还是科学上网解决的.我有段时间没看这个项目了,也不知道他们现在提供手工添加模型文件的方案没有.在国内搞AI还是要想没办法科学上网的.

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年12月3日 23:11
收件人: ***@***.***>
抄送: ***@***.***>; State ***@***.***>
主题: Re: [Plachtaa/VALL-E-X] Add Vocos information to the README. (Issue #89)


@hkzbiyx<https://github.com/hkzbiyx> I have downloaded these two files from other channels and am currently researching their paths in a Linux environment. I am using Raspberry Pi

Where did you download these two files? I also cannot access huggingface.co

―

**Comment by hkzbiyx** [comment]
> > @hkzbiyx I have downloaded these two files from other channels and am currently researching their paths in a Linux environment. I am using Raspberry Pi
> 
> Where did you download these two files? I also cannot access huggingface.co

Download this file.
https://pan.baidu.com/s/123sbEQRvbWJrx728JwgqSg?pwd=h2gi

If you're on Linux, run this:
`tar zxvf vocos.tar.gz -C ~/.cache/huggingface/hub`

If you're on Windows, please unzip the file to this directory:
`C:\Users\%username%\.cache\huggingface\hub\models--charactr--vocos-encodec-24khz\`
